const Projects = [
    {
        id: '1',
        slug: 'Maria-Robin',
        title:'Maria & Robin',
        pimg1:'/images/portfolio/prueba.jpg',
        pSimg:'/images/portfolio/i6.jpg',
        date:'Feb 2019',
        location:'Austria',
    },
    {
        id: '2',
        slug: 'Maria-Robin',
        title:'Maria & Robin',
        pimg1:'/images/portfolio/1.jpg',
        pSimg:'/images/portfolio/i6.jpg',
        date:'Feb 2019',
        location:'Austria',
    },
    {
        id: '3',
        slug: 'Maria-Robin',
        title:'Maria & Robin',
        pimg1:'/images/portfolio/1.jpg',
        pSimg:'/images/portfolio/i6.jpg',
        date:'Feb 2019',
        location:'Austria',
    },
    {
        id: '4',
        slug: 'Rose-Harry',
        title:'Rose & Harry',
        pimg1:'/images/portfolio/2.jpg',
        pSimg:'/images/portfolio/i5.jpg',
        date:'Feb 2019',
        location:'Austria',
    },
    {
        id: '5',
        slug: 'Rose-Harry',
        title:'Rose & Harry',
        pimg1:'/images/portfolio/prueba.jpg',
        pSimg:'/images/portfolio/i5.jpg',
        date:'Feb 2019',
        location:'Austria',
    },
    {
        id: '6',
        slug: 'Rose-Harry',
        title:'Rose & Harry',
        pimg1:'/images/portfolio/2.jpg',
        pSimg:'/images/portfolio/i5.jpg',
        date:'Feb 2019',
        location:'Austria',
    },
    {
        id: '7',
        slug: 'Maria-Nevela',
        title:'Maria & Nevela',
        pimg1:'/images/portfolio/6.jpg',
        pSimg:'/images/portfolio/i7.jpg',
        date:'Feb 2019',
        location:'Austria',
    },
    {
        id: '8',
        slug: 'Maria-Nevela',
        title:'Maria & Nevela',
        pimg1:'/images/portfolio/6.jpg',
        pSimg:'/images/portfolio/i7.jpg',
        date:'Feb 2019',
        location:'Austria',
    },
    {
        id: '9',
        slug: 'Maria-Nevela',
        title:'Maria & Nevela',
        pimg1:'/images/portfolio/prueba.jpg',
        pSimg:'/images/portfolio/i7.jpg',
        date:'Feb 2019',
        location:'Austria',
    },



    {
        id: '10',
        pimg1:'/images/portfolio/i5.jpg',
    },
    {
        id: '11',
        pimg1:'/images/portfolio/i9.jpg',
    },
    {
        id: '12',
        pimg1:'/images/portfolio/i10.jpg',
    },
    {
        id: '13',
        pimg1:'/images/portfolio/i11.jpg',
    },
    {
        id: '14',
        pimg1:'/images/portfolio/aereo.jpg',
    },
    {
        id: '15',
        pimg1:'/images/portfolio/hotel.jpg',
    },



    {
        id: '16',
        title:'Gabriela & Jorge',
        slug: 'Gabriela-Jorge',
        pSimg:'/images/portfolio/i1.jpg',
        pimg1:'/images/portfolio/i1.jpg',
        pimg2:'/images/portfolio/hotel.jpg',
        pimg3:'/images/portfolio/aereo.jpg',
        pimg4:'/images/portfolio/hotel.jpg',
        date:'Octubre 2022',
        desc:'En el idílico escenario de Barceló Riviera Maya, en octubre de 2022, una pareja decidió sellar su amor frente a las aguas turquesa del Caribe mexicano. Entre palmeras que susurraban historias al viento y playas de arena blanca que reflejaban la luminosidad del día, prometieron cuidarse y amarse por el resto de sus vidas. Invitados de todas partes del mundo, tocados por la magia del momento, fueron testigos de una unión que tenía el aroma salado del mar y el ritmo suave de las olas. El resort Barceló, con su perfecta amalgama de naturaleza y lujo, sirvió como el telón de fondo para el inicio de una nueva aventura para la pareja, una que, sin duda, estará llena de amor, risas y recuerdos inolvidables.',
        location:'Barceló Riviera Maya',
    },
    {
        id: '17',
        title:'Maite y Raúl',
        slug: 'Maite-Raúl',
        pSimg:'/images/portfolio/i2.jpg',
        pimg1:'/images/portfolio/i2.jpg',
        date:'Mayo 2022',
        desc:'Bajo el sol radiante de mayo de 2022, en el majestuoso Barceló Maya Palace, dos almas se encontraron en el altar, prometiendo un amor eterno y inquebrantable. Rodeados de la arquitectura colonial y el lujo sofisticado del resort, intercambiaron votos con el Mar Caribe como testigo silente, cuyas aguas cristalinas brillaban especialmente aquel día. Los invitados, envueltos en la atmósfera de romance y elegancia que solo un lugar como Barceló Maya Palace puede ofrecer, brindaron y celebraron por la unión de una pareja que decidió empezar su viaje juntos en uno de los paraísos más impresionantes del mundo. Aquella boda, marcada por la brisa suave y las melodías de la costa, quedará grabada en la memoria de todos como el inicio perfecto de un amor sin fin.',
        location:'Barceló Maya Palace',
    },
    {
        id: '18',
        title:'Sandra y Christian',
        slug: 'Sandra-Christian',
        pSimg:'/images/portfolio/i3.jpg',
        pimg1:'/images/portfolio/i3.jpg',
        date:'Mayo 2022',
        desc:'En mayo de 2022, rodeados por la magia y esencia de Xcaret, una pareja eligió consolidar su amor eterno entre las selvas y aguas cristalinas de uno de los destinos más emblemáticos de México. Mientras las melodías ancestrales de la tierra maya flotaban en el aire, prometieron cuidarse mutuamente en la alameda del parque, con sus seres queridos y la vasta naturaleza como testigos privilegiados. Las aves exóticas parecían cantar en celebración, y los reflejos del agua daban un brillo especial al ambiente, emulando los destellos de esperanza y amor en los ojos de la pareja. Aquel día en Xcaret no solo fue el inicio de una vida juntos para ellos, sino también una oda a la tradición, cultura y belleza natural de México. Una ceremonia que, sin duda, quedará en los corazones de todos como un recuerdo imperecedero de un amor tan profundo como las raíces de ese magnífico lugar.',
        location:'Xcaret México',
    },
    {
        id: '19',
        title:'Vania y Diego',
        slug: 'Vania-Diego',
        pSimg:'/images/portfolio/i4.jpg',
        pimg1:'/images/portfolio/i4.jpg',
        date:'Septiembre 2022',
        desc:'En el radiante mes de septiembre de 2022, las costas doradas de Punta Cana se convirtieron en el escenario de ensueño para una pareja que, con el resplandeciente mar Caribe como telón de fondo, unió sus almas para siempre en el lujoso resort RIU. Las palmeras mecidas por el viento y el suave arrullo de las olas compusieron una melodía natural que enmarcó un "sí, acepto" lleno de pasión y compromiso. Rodeados por la calidez de sus seres queridos y la hospitalidad característica de la República Dominicana, celebraron el amor en una fiesta que, bajo el cielo estrellado de Punta Cana, brilló con luz propia. Aquel día, la pareja no solo prometió amor eterno, sino que también selló un recuerdo inolvidable, donde el lujo del RIU y la magia del Caribe se fusionaron en una celebración perfecta de amor y alegría.',
        location:'RIU Punta Cana',
    },
    {
        id: '20',
        title:'Vivi y Rudy',       
        slug: 'Vivi-Rudy', 
        pSimg:'/images/portfolio/i5.jpg',
        pimg1:'/images/portfolio/i5.jpg',
        date:'Noviembre 2022',
        desc:'Noviembre de 2022 vio florecer una historia de amor en uno de los rincones más mágicos de México: Xcaret. Esta pareja eligió el corazón de la Riviera Maya para sellar su compromiso, rodeados por la exuberante naturaleza y las aguas cristalinas de los cenotes sagrados. En un ambiente donde la cultura y tradiciones mexicanas se entrelazan con paisajes de ensueño, pronunciaron sus votos en medio de antiguas ruinas mayas y flamantes mariposas. Acompañados de familiares y amigos, y con el sonido de las marimbas resonando a lo lejos, celebraron su unión en una fiesta que evocaba lo mejor de México. Aquella boda no solo representó el inicio de una nueva etapa para la pareja, sino que también se convirtió en un tributo al amor puro y auténtico, tan intenso y vibrante como los colores de Xcaret en otoño.',
        location:'Xcaret México',
    },
    {
        id: '21',
        title:'Yasmin y Kenneth',
        slug: 'Yasmin-Kenneth',
        pSimg:'/images/portfolio/i6.jpg',
        pimg1:'/images/portfolio/i6.jpg',
        date:'Mayo 2023',
        desc:'Mayo de 2023 quedará grabado en los corazones de todos los presentes en Bahía Príncipe Punta Cana. En este paraíso dominicano, donde las palmeras se mecen al ritmo de la brisa y el sol acaricia la arena dorada, una pareja decidió unir sus destinos. Eligieron este refugio de ensueño, con su majestuosa vista al Caribe, para intercambiar promesas y miradas llenas de futuro. Al caer la tarde, bajo un cielo teñido de naranja y rosa, sus voces resonaron con votos sinceros, mientras el suave murmullo de las olas aplaudía su unión. Rodeados de seres queridos, la alegría y los bailes se extendieron hasta el alba. Aquel día, en Bahía Príncipe, no solo se celebró un matrimonio, sino también el triunfo del amor verdadero, la pasión y la promesa de innumerables mañanas compartidas en la dulce melodía del Caribe.',
        location:'Bahía Príncipe Punta Cana',
    },
    {
        id: '22',
        title:'Yuuko y Yuki',
        slug:'Yuuko-Yuki',
        pSimg:'/images/portfolio/i7.jpg',
        pimg1:'/images/portfolio/i7.jpg',
        date:'Mayo 2023',
        desc:'Mayo de 2023 fue testigo de un amor inquebrantable en las enigmáticas tierras de Xcaret, México. En medio de un ambiente donde la cultura y naturaleza convergen, una pareja decidió plasmar su historia de amor eterno. Rodeados de la rica biodiversidad y los misterios ancestrales del lugar, intercambiaron sus votos bajo el cobijo de ceibas centenarias y al ritmo de melodías prehispánicas. El eco de sus promesas se fundió con el canto de las aves y el susurro del mar Caribe cercano. A medida que la luz del atardecer bañaba las aguas cristalinas de los cenotes, los recién casados y sus seres queridos celebraron, danzaron y brindaron por un futuro juntos. En Xcaret, no solo se unieron dos almas, sino que también se entrelazó la magia de México con la promesa de un amor que trasciende el tiempo.',
        location:'Xcaret México',
    }
    // {
    //     id: '23',
    //     title:'8',
    //     pimg1:'/images/portfolio/i8.jpg',
    // },
    // {
    //     id: '24',
    //     title:'9',
    //     pimg1:'/images/portfolio/i9.jpg',
    // },
    // {
    //     id: '25',
    //     title:'10',
    //     pimg1:'/images/portfolio/i10.jpg',
    // }
]
export default Projects;